version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app/airbnb-mongo
permissions:
  - object: /home/ec2-user
    pattern: '**'
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root
