version: "3.7"

services:
  app:
    image: airbnb-mongo
    container_name: airbnb-mongo
    ports:
      - 8090:8090
  mongo:
    image: mongo:5.0
    container_name: airbnb-mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret