# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Make zip file
      run: zip -qq -r ./$GITHUB_SHA.zip .
      shell: bash  

    - name: Set up AWS
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.MONGO_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.MONGO_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to AWS S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://airbnb-mongo/$GITHUB_SHA.zip
      
    - name: Run AWS CodeDeploy
      run: aws deploy create-deployment -—application-name airbnb-mongo —deployment-config-name CodeDeployDefault.OneAtATime —deployment-group-name develop —s3-location bucket=airbnb-mongo,bundleType=zip,key=airbnb-mongo/$GITHUB_SHA.zip
